### ISSUE TITLE
Apparent typo in Color.blacken docs

### ISSUE THREAD

**Issue by ianmackenzie** [tesk9/palette#22]
I'm guessing this should say "decreases" instead of "increases": https://github.com/tesk9/palette/blob/e2b8e277ccab4b09bcb3b11833f6ffcec6cf859a/src/Color.elm#L394

Great package, by the way! I really like the fact that you have separate types for color with and without transparency. I'm planning to switch my `elm-3d-scene` package over to using this package's `Color` type since that cleans up some ambiguity in the `elm-3d-scene` API where I don't actually support transparency (and I think the various palettes and palette generation functions could also be useful in setting up certain kinds of 3D scenes).

**Comment by tesk9** [comment]
Thank you!!
