### ISSUE TITLE
Color from a hex string

### ISSUE THREAD

**Issue by kalawr** [tesk9/palette#3]
Hi there! Thank you for the great work you've done on this library. In the app we are building we are importing a bunch of hex colors from the database. Ideally, we would want to create some derivatives of these colors on the front-end side. Do you think Palette could use a Color.fromHex function to help with this? I would be happy to provide a PR if you think such addition could be good for the library :)

**Comment by tesk9** [comment]
Oh yes! That would be wonderful!

**Comment by tesk9** [comment]
I'm working on this today
